# Create a workbench

Inside the new project, we can create different components. One of them, and probably the most important one when it comes to model training, will be the Workbench. A workbench is a containerized workspace that operates within a pod and contains a collection of different AI/ML libraries and a JupyterLab server.

1. There are different tabs inside our project page. Click on **Workbenches**.
2. On there, select the **Create workbench** button to open the configuration window.
3. Complete the fields depending on your use case specifications:
    * **Name**: Type your preferred name. I will use `model-training`.
    * **Image selection**: the election will depend on your model requirements. Click on View package information to see the packages included. I will use `Pytorch`.
    * **Version selection**: The recommendation is to use the latest package versions. For me, those will be the `2024.1` version.
    * **Container size**: Select it according to your hardware limitations: number of CPUs, memory, and request capacity of the container. In my case, `Medium`.
    * **Accelerator**: Remember to use the NFD and the NVIDIA operators to expose your graphic cards. My drop-down menu shows `NVIDIA GPU`.
    * **Number of accelerators**: Select as many graphic cards as available in your node. The machine where my SNO was installed hosts `2` GPUs.
    * Check the Create new persistent storage box.
        ** **Name**: Type any desired name for the persistent volume. For example, `model-training-pv`.
        ** **Persistent storage size**: Specify the desired capacity for the volume. I will start with `20GB`, but we can always expand it if necessary.
4. Right now, I will not attach any Data Connection to this workbench. We will see how to set up and use object storage in the next section of this article.
5. Review your configuration and press **Create workbench**. This last step will trigger the workbench creation.
6. You will be automatically redirected to another page where you can track the workbench deployment process. Wait until the Status shows *Running* and click **Open**.
7. Finally, enter your credentials to authenticate to the workbench's JupyterLab.

Now it's your turn to start creating your custom Notebooks to build and train your AI model. And for this, we will need to have a s3 storage to store these models.

## Clone the Git repository

Usually, model training is the most time-consuming part and setting up the right parameters is crucial for an adequate performance. For this purpose, in this link:https://github.com/dialvare/ai-edge-lifecycle.git[GitHub repository] I have prepared the necessary datasets and notebooks to train, validate and save a model that is able to predict values over time, based on past samples and new values coming from external variables. Follow these steps to clone the repository inside our Jupyter environment.

1. Access your workbench's JupyterLab. In the toolbar on the left, in the third position you will find the **Git** icon. Click it.
2. In the new menu, select the **Clone repository** option. You will be asked to type the URL to the repo. Copy and paste this one:

[source,bash]
----
   https://github.com/dialvare/ai-edge-lifecycle.git
----
[start=3]
1. Click **Clone** to start pulling the contents. You can navigate through the different folders on the left section.
